import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./components/SessionWrapper";
import { Providers } from "./redux/providers";
import TokenInitializer from "./components/TokenInitializer";
import { SocketProvider } from "./components/SocketProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <SessionWrapper>
            <SocketProvider>
              {children}
            </SocketProvider>
          </SessionWrapper>
        </Providers>
      </body>
    </html>
  );
}
