import "./globals.css";
import { SessionWrapper } from "./components/SessionWrapper";
import { Providers } from "./redux/providers";
import { SocketProvider } from "./components/SocketProvider";


export const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <SessionWrapper>
            <SocketProvider>
              {children}
            </SocketProvider>
          </SessionWrapper>
        </Providers>
      </body>
    </html>
  );
}
